import Head from 'next/head'
import Main from '@/components/Main/Main'

import { getCookie, deleteCookie, setCookie } from "cookies-next"

import { useRouter } from 'next/router';

export default function Home() {

  const router = useRouter();

  const UserRegisterationRequestMainHandler = (data) => {
    
      const { responseData } = data;
      const { responseObject, status, token } = responseData;

      if(responseObject !== null && status === 200) {
        setCookie('USER_AUTH_TOKEN', token);
        setCookie('USER_AUTH_USERNAME', responseObject.username);
        
        router.push("/dashboard");
      }
  };

  const UserAuthRequestMainHandler = (data) => {
       
    const { responseData } = data;
    const { responseObject, status, token } = responseData;

    if(responseObject !== null && status === 200) {
      setCookie('USER_AUTH_TOKEN', token);
      setCookie('USER_AUTH_USERNAME', responseObject.username);      
      
      router.push("/dashboard");
    }
};
 
  return (
    <>
      <Head>
        <title>Venus Memo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>        
        <Main onUserRegisterationRequestMain={UserRegisterationRequestMainHandler}  
              onUserAuthRequestMain={UserAuthRequestMainHandler}/>
      </main>
    </>
  )
}

export const getServerSideProps = ({ req, res }) => {

  const option = { req, res};
  const token = getCookie("USER_AUTH_TOKEN", option);

  if(token != undefined && token !== "" && token != null) {
       return {
         redirect: {
           permanent: false,
           destination: "/dashboard",
         },
         props:{},
       }
  }

  return {
     props: {
     }
  }
};
